name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
      - develop # Déclenche le workflow sur chaque push vers la branche main
  pull_request:
    branches:
      - main  # Déclenche le workflow sur chaque pull request vers la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Check out le code de votre repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou toute autre version de Node.js que vous utilisez

      # Étape 3 : Se déplacer dans le répertoire 'beer-pong-cv' (dossier de l'application React)
      - name: Change directory to beer-pong-cv
        run: cd beer-pong-cv

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: |
          cd beer-pong-cv
          npm install
          
      # Étape 5 : Installer gh-pages
      - name: Install gh-pages
        run: |
          cd beer-pong-cv
          npm install gh-pages --save-dev

      # Étape 6 : Construire le projet dans le répertoire correct
      - name: Build
        run: |
          cd beer-pong-cv
          npm run build
          
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Étape 7 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          cd beer-pong-cv
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token GitHub pour le déploiement